//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 06:02:48 PM IST 
//


package org.mismo.residential._2009.schemas;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * MESSAGE is the root node for V3. It represents the message payload of any SOAP or REST transaction.  In SOAP MESSAGE is the content of &gt;soap:body&lt;.  In REST MESSSAGE is the document that is in the PUT, GET or DELETE HTTP protocol methods.
 * 
 * <p>Java class for MESSAGE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MESSAGE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ABOUT_VERSIONS" type="{http://www.mismo.org/residential/2009/schemas}ABOUT_VERSIONS"/>
 *         &lt;element name="DOCUMENT_SETS" type="{http://www.mismo.org/residential/2009/schemas}DOCUMENT_SETS"/>
 *       &lt;/sequence>
 *       &lt;attribute name="MISMOReferenceModelIdentifier" type="{http://www.mismo.org/residential/2009/schemas}MISMOReferenceModelIdentifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "MESSAGE")
public class MESSAGE implements Serializable{

 
	private static final long serialVersionUID = 7186408767864335762L;
	
	@XmlElement(name = "ABOUT_VERSIONS", required = true)
    protected ABOUTVERSIONS aboutversions;
    @XmlElement(name = "DOCUMENT_SETS", required = true)
    protected DOCUMENTSETS documentsets;
    @XmlAttribute(name = "MISMOReferenceModelIdentifier")
    protected String mismoReferenceModelIdentifier;
   
    /**
     * Gets the value of the aboutversions property.
     * 
     * @return
     *     possible object is
     *     {@link ABOUTVERSIONS }
     *     
     */
    public ABOUTVERSIONS getABOUTVERSIONS() {
        return aboutversions;
    }

    /**
     * Sets the value of the aboutversions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABOUTVERSIONS }
     *     
     */
    public void setABOUTVERSIONS(ABOUTVERSIONS value) {
        this.aboutversions = value;
    }

    /**
     * Gets the value of the documentsets property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTSETS }
     *     
     */
    public DOCUMENTSETS getDOCUMENTSETS() {
        return documentsets;
    }

    /**
     * Sets the value of the documentsets property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTSETS }
     *     
     */
    public void setDOCUMENTSETS(DOCUMENTSETS value) {
        this.documentsets = value;
    }

    /**
     * Gets the value of the mismoReferenceModelIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMISMOReferenceModelIdentifier() {
        return mismoReferenceModelIdentifier;
    }

    /**
     * Sets the value of the mismoReferenceModelIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMISMOReferenceModelIdentifier(String value) {
        this.mismoReferenceModelIdentifier = value;
    }

}
